#! /bin/sh

# wmnae, "error": "Remote control is disabled. Add allow_remote_control to your kitty.conf"}e i3 &
wal -i /home/b/winvst/7effd75f22168dac7085c7c900adbf89.jpg & --saturate 0.6
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color6"
bspc config presel_feedback_color "$color1"
pgrep polybar || polybar topright &
pgrep polybar || polybar topleft &
pgrep compton || compton --blur-method dual_kawase --respect-prop-shadow &
#/home/b/.config/polybar/launch.sh &
sleep 5 && deluge-gtk &
nm-applet &
xset s off -dpms
xset s off
thunar --daemon &
dunst &
pgrep qjackctl || qjackctl -a /home/b/dt990eq.xml &
sleep 9 && pgrep carla || carla /home/b/dt990eq.carxp &
pgrep a2jmidid || a2jmidid -e &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap          12
#bspc config focused_border_color '#8acbdb'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a carla-bridge-win64.exe state=floating

bspc rule -a QjackCtl state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a origin.exe state=floating
bspc rule -a Carla-bridge-lv2-gtk2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a spotify state=floating
#kitty --class scratchterm -e ~/scratchtermtoggle &
#bspc rule -a scratchtermtoggle sticky=on state=floating hidden=true 
#bspc config focus_follows_pointer true
